name: Update GitHub Stats

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch GitHub Contribution Data
        run: |
          RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GH_STATS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/users/OskaraOskar)

          PRIVATE_CONTRIBS=$(curl -s -H "Authorization: token ${{ secrets.GH_STATS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/user \
            | jq '.total_private_repos')

          PUBLIC_CONTRIBS=$(echo $RESPONSE | jq '.public_repos')
          FOLLOWERS=$(echo $RESPONSE | jq '.followers')

          # Handle API failures
          if [[ -z "$PRIVATE_CONTRIBS" ]]; then PRIVATE_CONTRIBS="N/A"; fi
          if [[ -z "$PUBLIC_CONTRIBS" ]]; then PUBLIC_CONTRIBS="N/A"; fi
          if [[ -z "$FOLLOWERS" ]]; then FOLLOWERS="N/A"; fi

          echo "PRIVATE_CONTRIBS=$PRIVATE_CONTRIBS" >> $GITHUB_ENV
          echo "PUBLIC_CONTRIBS=$PUBLIC_CONTRIBS" >> $GITHUB_ENV
          echo "FOLLOWERS=$FOLLOWERS" >> $GITHUB_ENV

      - name: Generate SVG Stats
        run: |
          echo '<svg width="500" height="250" xmlns="http://www.w3.org/2000/svg">
          <text x="10" y="30" font-size="20" fill="white">📊 GitHub Activity Stats</text>
          <text x="10" y="70" font-size="18" fill="cyan">👥 Followers: '"${FOLLOWERS}"'</text>
          <text x="10" y="100" font-size="18" fill="green">🗂 Public Repos: '"${PUBLIC_CONTRIBS}"'</text>
          <text x="10" y="130" font-size="18" fill="orange">🔒 Private Contributions: '"${PRIVATE_CONTRIBS}"'</text>
          <text x="10" y="180" font-size="12" fill="gray">Last updated: '"$(date -u)"' UTC</text>
          </svg>' > dist/github-stats.svg

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add dist/github-stats.svg
          git commit -m "Auto-update GitHub stats" || echo "No changes to commit"
          git push || echo "No changes to push"

      - name: Fallback Update with GitHub Readme Stats
        if: failure()
        run: |
          echo "Primary update failed. Falling back to Readme Stats API"
          curl -s "https://github-readme-stats.vercel.app/api?username=OskaraOskar&show_icons=true&count_private=true&theme=radical" -o dist/github-stats.svg

          git add dist/github-stats.svg
          git commit -m "Fallback update via Readme Stats"
          git push || echo "No fallback changes to push"
