name: Update GitHub Profile Assets

on:
  schedule:
    - cron: '* */12 * * *'  # Runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update profile assets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Contribution Grid
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: OskaraOskar
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Deploy Snake Contribution Grid to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_STATS_TOKEN }}

      - name: Fetch 3D Contribution Graph
        run: |
          curl -o dist/profile-3d-contrib.svg "https://github-profile-summary-cards.vercel.app/api/cards/profile-details?username=OskaraOskar&theme=tokyonight"

      - name: Fetch Random Dev Quote
        run: |
          curl -o dist/github-quote.svg "https://quotes-github-readme.vercel.app/api?type=horizontal&theme=tokyonight"

      - name: Fetch GitHub Stats (Including Private Repos)
        env:
          GH_STATS_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
        run: |
          curl -o dist/github-stats.svg "https://github-readme-stats.vercel.app/api?username=OskaraOskar&show_icons=true&theme=tokyonight&hide=stars&include_all_commits=true&count_private=true&token=${GH_STATS_TOKEN}"
          curl -o dist/top-langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=OskaraOskar&layout=compact&theme=tokyonight&langs_count=8&count_private=true&token=${GH_STATS_TOKEN}"
          curl -o dist/streak-stats.svg "https://streak-stats.demolab.com?user=OskaraOskar&theme=tokyonight&count_private=true&token=${GH_STATS_TOKEN}"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg dist/profile-3d-contrib.svg dist/github-quote.svg dist/github-stats.svg dist/top-langs.svg dist/streak-stats.svg || echo "No changes to add"
          git commit -m "Update GitHub Profile Assets [Automated]" || echo "No changes to commit"
          git push || echo "No changes to push"
